import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Algolendar",
  description: "Generated by ghlee",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>{children}</body>
    </html>
  );
}
