import "./globals.css";
import type { Metadata } from "next";
import Logo from "@/components/common/Logo";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Algolendar",
  description: "Generated by ghlee",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <header className="p-4">
          <Link href="/">
            <Logo size={30} />
          </Link>
        </header>
        {children}
      </body>
    </html>
  );
}
